version: "3.9"
services:  
  webapp:   
    build: .
    ports:
      - 8081:8080
    volumes:
      - ./src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    command : run serve
    environment:
      - VUE_APP_CHATBOT_BACKEND_URL=http://localhost:8030